apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-service
  namespace: {{ .Values.global.namespace }}

spec:
  replicas: {{ .Values.notification.replicaCount }}

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      serviceAccountName: {{ .Values.notification.serviceAccount.name }}

      containers:
        - name: notification-service

          image: "{{ .Values.notification.image.repository }}:{{ .Values.notification.image.tag }}"

          imagePullPolicy: {{ .Values.notification.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.notification.service.targetPort }}

          envFrom:
            - configMapRef:
                name: notification-service-config

          resources:
            requests:
              cpu: {{ .Values.notification.resources.requests.cpu | quote }}
              memory: {{ .Values.notification.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.notification.resources.limits.cpu | quote }}
              memory: {{ .Values.notification.resources.limits.memory | quote }}

          startupProbe:
            httpGet:
              path: {{ .Values.notification.probes.startup.path }}
              port: {{ .Values.notification.service.targetPort }}
            periodSeconds: {{ .Values.notification.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.notification.probes.startup.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.notification.probes.readiness.path }}
              port: {{ .Values.notification.service.targetPort }}
            periodSeconds: {{ .Values.notification.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.notification.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.notification.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.notification.probes.liveness.path }}
              port: {{ .Values.notification.service.targetPort }}
            periodSeconds: {{ .Values.notification.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.notification.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.notification.probes.liveness.failureThreshold }}