apiVersion: apps/v1
kind: Deployment

metadata:
  name: scanning-service
  namespace: {{ .Values.global.namespace }}

spec:
  replicas: {{ .Values.scanning.replicaCount }}

  selector:
    matchLabels:
      app: scanning-service

  template:
    metadata:
      labels:
        app: scanning-service

    spec:
      serviceAccountName: {{ .Values.scanning.serviceAccount.name }}

      containers:
        - name: scanning-service

          image: "{{ .Values.scanning.image.repository }}:{{ .Values.scanning.image.tag }}"

          imagePullPolicy: {{ .Values.scanning.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.scanning.service.targetPort }}

          envFrom:
            - configMapRef:
                name: scanning-service-config

          resources:
            requests:
              cpu: {{ .Values.scanning.resources.requests.cpu | quote }}
              memory: {{ .Values.scanning.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.scanning.resources.limits.cpu | quote }}
              memory: {{ .Values.scanning.resources.limits.memory | quote }}

          startupProbe:
            httpGet:
              path: {{ .Values.scanning.probes.startup.path }}
              port: {{ .Values.scanning.service.targetPort }} 
            periodSeconds: {{ .Values.scanning.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.scanning.probes.startup.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.scanning.probes.readiness.path }}
              port: {{ .Values.scanning.service.targetPort }}
            periodSeconds: {{ .Values.scanning.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.scanning.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.scanning.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.scanning.probes.liveness.path }}
              port: {{ .Values.scanning.service.targetPort }}
            periodSeconds: {{ .Values.scanning.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.scanning.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.scanning.probes.liveness.failureThreshold }}