apiVersion: v1
kind: Service

metadata:
  name: scanning-service
  namespace: {{ .Values.global.namespace }}

spec:
  type: ClusterIP

  selector:
    app: scanning-service

  ports:
    - port: {{ .Values.scanning.service.port }}
      targetPort: {{ .Values.scanning.service.targetPort }}