global:
  namespace: staging

scanning:
  replicaCount: 2

  image:
    repository: 386566550877.dkr.ecr.ca-central-1.amazonaws.com/cloud-operations-scanning-service
    tag: v1.0.1
    pullPolicy: IfNotPresent

  service:
    port: 80
    targetPort: 3000

  serviceAccount:
    name: scanning-service-account

  config:
    APP_NAME: scanning-service
    PORT: "3000"
    ENVIRONMENT: staging

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

  probes:
    startup:
      path: /healthz
      periodSeconds: 5
      failureThreshold: 12

    readiness:
      path: /healthz
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3

    liveness:
      path: /healthz
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3

licensing:
  replicaCount: 2

  image:
    repository: 386566550877.dkr.ecr.ca-central-1.amazonaws.com/cloud-operations-licensing-service
    tag: v1.0.1
    pullPolicy: IfNotPresent

  service:
    port: 80
    targetPort: 3000

  serviceAccount:
    name: licensing-service-account

  config:
    APP_NAME: licensing-service
    PORT: "3000"
    ENVIRONMENT: staging

  resources:
    requests:
      cpu: "75m"
      memory: "96Mi"
    limits:
      cpu: "200m"
      memory: "192Mi"

  probes:
    startup:
      path: /healthz
      periodSeconds: 5
      failureThreshold: 12

    readiness:
      path: /healthz
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3

    liveness:
      path: /healthz
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3

notification:
  replicaCount: 1

  image:
    repository: 386566550877.dkr.ecr.ca-central-1.amazonaws.com/cloud-operations-notification-service
    tag: v1.0.1
    pullPolicy: IfNotPresent

  service:
    port: 80
    targetPort: 3000

  serviceAccount:
    name: notification-service-account

  config:
    APP_NAME: notification-service
    PORT: "3000"
    ENVIRONMENT: staging

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "150m"
      memory: "128Mi"

  probes:
    startup:
      path: /healthz
      periodSeconds: 5
      failureThreshold: 12

    readiness:
      path: /healthz
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3

    liveness:
      path: /healthz
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3